### ISSUE TITLE
[Error] : Unable to install in Virtualbox?

### ISSUE THREAD

**Issue by byteshiva** [xmm15/ZenithOS#3]
I'm unable to install `zenithos` on virtualbox.  after successful installation reboot it goes again and asks whether to install on HD etc.

Am I missing something here?  
 
![image](https://user-images.githubusercontent.com/10637299/75126998-9031c580-56e2-11ea-8a3b-c62fded05782.png)

**Comment by xmm15** [comment]
After you successfully install, you're supposed to remove the ISO from the virtual CD drive.
Right-Click on the little CD icon on the bottom status bar of the VM window and click "Remove disk from virtual drive".

It's the same as making a windows installer USB, booting it on your computer, installing windows, and after it's finished, it boots back to the installer because you left the USB plugged in.

**Comment by byteshiva** [comment]
> Remove disk from virtual drive".

Thanks It worked
